-- MySQL Script generated by MySQL Workbench
-- Wed 01 Jul 2020 23:10:03 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema logistic_transporte
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `logistic_transporte` ;

-- -----------------------------------------------------
-- Schema logistic_transporte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logistic_transporte` DEFAULT CHARACTER SET utf8 ;
USE `logistic_transporte` ;

-- -----------------------------------------------------
-- Table `logistic_transporte`.`comuna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logistic_transporte`.`comuna` ;

CREATE TABLE IF NOT EXISTS `logistic_transporte`.`comuna` (
  `idcomuna` INT NOT NULL,
  `nombre_comuna` VARCHAR(450) NOT NULL,
  `created_comuna` DATETIME NOT NULL,
  `edited_comuna` DATETIME NOT NULL,
  PRIMARY KEY (`idcomuna`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistic_transporte`.`chofer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logistic_transporte`.`chofer` ;

CREATE TABLE IF NOT EXISTS `logistic_transporte`.`chofer` (
  `idchofer` INT NOT NULL,
  `nombre_chofer` VARCHAR(450) NOT NULL,
  `rut_chofer` VARCHAR(45) NOT NULL,
  `created_chofer` DATETIME NOT NULL,
  `edited_chofer` DATETIME NOT NULL,
  PRIMARY KEY (`idchofer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistic_transporte`.`reparto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logistic_transporte`.`reparto` ;

CREATE TABLE IF NOT EXISTS `logistic_transporte`.`reparto` (
  `idreparto` INT NOT NULL,
  `paquetes_inicial` INT NOT NULL,
  `paquetes_pendiente` INT NOT NULL,
  `paquetes_entregados` INT NOT NULL,
  `fecha_reparto` DATETIME NOT NULL,
  `comuna` INT NOT NULL,
  PRIMARY KEY (`idreparto`),
  INDEX `fk_reparto_comuna_idx` (`comuna` ASC),
  CONSTRAINT `fk_reparto_comuna`
    FOREIGN KEY (`comuna`)
    REFERENCES `logistic_transporte`.`comuna` (`idcomuna`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistic_transporte`.`reparto_chofer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logistic_transporte`.`reparto_chofer` ;

CREATE TABLE IF NOT EXISTS `logistic_transporte`.`reparto_chofer` (
  `chofer` INT NOT NULL,
  `reparto` INT NOT NULL,
  `status_reparto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`chofer`, `reparto`),
  INDEX `fk_chofer_has_reparto_reparto1_idx` (`reparto` ASC),
  INDEX `fk_chofer_has_reparto_chofer1_idx` (`chofer` ASC),
  CONSTRAINT `fk_chofer_has_reparto_chofer1`
    FOREIGN KEY (`chofer`)
    REFERENCES `logistic_transporte`.`chofer` (`idchofer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_chofer_has_reparto_reparto1`
    FOREIGN KEY (`reparto`)
    REFERENCES `logistic_transporte`.`reparto` (`idreparto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
